name: railsy_time
description: Convenient date/time extension methods inspired by Ruby on Rails.
version: 1.0.0
repository: https://github.com/citizen428/railsy_time
issue_tracker: https://github.com/citizen428/railsy_time/issues
topics:
  - date
  - time

environment:
  sdk: ^3.0.1

dependencies:
  clock: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
